//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayzippyDotNetSDK {
    
    
    public partial class ChargeIframe {
        
     
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    }
}
