using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PayzippyDotNetSDK.payzippy_sdk
{
    public class Constants
    {
        public static readonly List<string> validPaymentMethods = new List<string> { "CREDIT", "DEBIT", "EMI", "NET", "PAYZIPPY" };
        public static readonly List<string> bankNameRequirement = new List<string> { "EMI", "NET" };
        public static readonly List<string> uiModeRequirements = new List<string> { "REDIRECT", "IFRAME" };
        public static readonly List<string> hashMethodRequirements = new List<string> { "SHA256", "MD5" };
        public static readonly List<string> transactionTypeCheck = new List<string> { "SALE", "REFUND" };
        public static readonly string MERCHANT_ID = "merchant_id";
        public static readonly string BUYER_EMAIL_ADDRESS = "buyer_email_address";
        public static readonly string MERCHANT_TRANSACTION_ID = "merchant_transaction_id";
        public static readonly string TRANSACTION_TYPE = "transaction_type";
        public static readonly string TRANSACTION_AMOUNT = "transaction_amount";
        public static readonly string PAYMENT_METHOD = "payment_method";
        public static readonly string BANK_NAME = "bank_name";
        public static readonly string EMI_MONTHS = "emi_months";
        public static readonly string CURRENCY = "currency";
        public static readonly string UI_MODE = "ui_mode";
        public static readonly string HASH_METHOD = "hash_method";
        public static readonly string HASH = "hash";
        public static readonly string MERCHANT_KEY_ID = "merchant_key_id";
        public static readonly string BUYER_PHONE_NO = "buyer_phone_no";
        public static readonly string BUYER_UNIQUE_ID = "buyer_unique_id";
        public static readonly string SHIPPING_ADDRESS = "shipping_address";
        public static readonly string SHIPPING_CITY = "shipping_city";
        public static readonly string SHIPPING_STATE = "shipping_state";
        public static readonly string SHIPPING_ZIP = "shipping_zip";
        public static readonly string SHIPPING_COUNTRY = "shipping_country";
        public static readonly string SOURCE = "source";
        public static readonly string CALLBACK_URL = "callback_url";
        public static readonly string BILLING_NAME = "billing_name";
        public static readonly string BILLING_ADDRESS = "billing_address";
        public static readonly string BILLING_CITY = "billing_city";
        public static readonly string BILLING_STATE = "billing_state";
        public static readonly string BILLING_ZIP = "billing_zip";
        public static readonly string BILLING_COUNTRY = "billing_country";
        public static readonly string MIN_SLA = "min_sla";
        public static readonly string IS_USER_LOGGED_IN = "is_user_logged_in";
        public static readonly string ADDRESS_COUNT = "address_count";
        public static readonly string SALES_CHANNEL = "sales_channel";
        public static readonly string ITEM_TOTAL = "item_total";
        public static readonly string ITEM_VERTICAL = "item_vertical";
        public static readonly string ITEM_COUNT = "item_count";
        public static readonly string TIMEGMT = "timegmt";
        public static readonly string UDF1 = "udf1";
        public static readonly string UDF2 = "udf2";
        public static readonly string UDF3 = "udf3";
        public static readonly string UDF4 = "udf4";
        public static readonly string UDF5 = "udf5";
        public static readonly string PAYZIPPY_TRANSACTION_ID = "payzippy_transaction_id";
        public static readonly string TRANSACTION_STATUS = "transaction_status";
        public static readonly string TRANSACTION_RESPONSE_CODE = "transaction_response_code";
        public static readonly string TRANSACTION_RESPONSE_MESSAGE = "transaction_response_message";
        public static readonly string TRANSACTION_CURRENCY = "transaction_currency";
        public static readonly string TRANSACTION_TIME = "transaction_time";
        public static readonly string FRAUD_ACTION = "fraud_action";
        public static readonly string FRAUD_DETAILS = "fraud_details";
        public static readonly string IS_INTERNATIONAL = "is_international";
        public static readonly string VERSION = "version";
        public static readonly string PAYZIPPY_SALE_TRANSACTION_ID = "payzippy_sale_transaction_id";
        public static readonly string REFUND_AMOUNT = "refund_amount";
        public static readonly string REFUND_REASON = "refund_reason";
        public static readonly string REFUNDED_BY = "refunded_by";
        public static readonly string STATUS_CODE = "status_code";
        public static readonly string STATUS_MESSAGE = "status_message";
        public static readonly string ERROR_CODE = "error_code";
        public static readonly string ERROR_MESSAGE = "error_message";
        public static readonly string REFUND_STATUS = "refund_status";
        public static readonly string REFUND_RESPONSE_CODE = "refund_response_code";
        public static readonly string REFUND_RESPONSE_MESSAGE = "refund_response_message";
        public static readonly string BANK_ARN = "bank_arn";
        public static readonly string TERMINAL_ID = "terminal_id";
        public static readonly string BANK_TRANSACTION_ID = "bank_transaction_id";
        public static readonly string DATA = "data";
        public static readonly string PRODUCT_INFO1 = "product_info1";
        public static readonly string PRODUCT_INFO2 = "product_info2";
        public static readonly string PRODUCT_INFO3 = "product_info3";
        public static readonly string SMS_NOTIFY_NUMBER = "sms_notify_number";
        public static readonly int MERCHANT_ID_MAXLEN = 32;
        public static readonly int BUYER_EMAIL_ADDRESS_MAXLEN = 100;
        public static readonly int MERCHANT_TRANSACTION_ID_MAXLEN = 100;
        public static readonly int MERCHANT_KEY_ID_MAXLEN = 20;
        public static readonly int BUYER_PHONE_NO_MAXLEN = 50;
        public static readonly int BUYER_UNIQUE_ID_MAXLEN = 100;
        public static readonly int SHIPPING_ADDRESS_MAXLEN = 100;
        public static readonly int SHIPPING_CITY_MAXLEN = 50;
        public static readonly int SHIPPING_STATE_MAXLEN = 50;
        public static readonly int SHIPPING_ZIP_MAXLEN = 50;
        public static readonly int SHIPPING_COUNTRY_MAXLEN = 50;
        public static readonly int SOURCE_MAXLEN = 20;
        public static readonly int CALLBACK_URL_MAXLEN = 256;
        public static readonly int BILLING_NAME_MAXLEN = 255;
        public static readonly int BILLING_ADDRESS_MAXLEN = 100;
        public static readonly int BILLING_CITY_MAXLEN = 50;
        public static readonly int BILLING_STATE_MAXLEN = 50;
        public static readonly int BILLING_ZIP_MAXLEN = 50;
        public static readonly int BILLING_COUNTRY_MAXLEN = 50;
        public static readonly int MIN_SLA_MAXLEN = 100;
        public static readonly int ADDRESS_COUNT_MAXLEN = 100;
        public static readonly int SALES_CHANNEL_MAXLEN = 100;
        public static readonly int ITEM_TOTAL_MAXLEN = 100;
        public static readonly int ITEM_VERTICAL_MAXLEN = 100;
        public static readonly int TIMEGMT_MAXLEN = 13;
        public static readonly int UDF1_MAXLEN = 100;
        public static readonly int UDF2_MAXLEN = 100;
        public static readonly int UDF3_MAXLEN = 100;
        public static readonly int UDF4_MAXLEN = 100;
        public static readonly int UDF5_MAXLEN = 100;
        public static readonly int PAYZIPPY_TRANSACTION_ID_MAXLEN = 20;
        public static readonly int TRANSACTION_STATUS_MAXLEN = 30;
        public static readonly int TRANSACTION_RESPONSE_CODE_MAXLEN = 30;
        public static readonly int REFUND_AMOUNT_MAXLEN = 20;
        public static readonly int REFUNDED_BY_MAXLEN = 100;
        public static readonly int PAYZIPPY_SALE_TRANSACTION_ID_MAXLEN = 20;
        public static readonly int REFUND_REASON_MAXLEN = 512;

    }
}
